# Site settings
title: Programming Fundamentals
email: reedcwilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to computer programming using the Python language.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://programming.reedcwilson.com" # the base hostname & protocol for your site
twitter_username: reedcwilson
github_username: reedcwilson

# Build settings
markdown: kramdown
